<a href="https://colab.research.google.com/github/Avnish3909/Tweet_Disaster-Intelligence-ML/blob/main/Tweet_Disaster_Intelligence_ML_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!wget https://www.dropbox.com/s/rsdr34l9xk9yean/socialmedia_relevant_cols.csv

--2023-11-24 18:19:41--  https://www.dropbox.com/s/rsdr34l9xk9yean/socialmedia_relevant_cols.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/rsdr34l9xk9yean/socialmedia_relevant_cols.csv [following]
--2023-11-24 18:19:42--  https://www.dropbox.com/s/raw/rsdr34l9xk9yean/socialmedia_relevant_cols.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucef4844c05faf416a67581341fc.dl.dropboxusercontent.com/cd/0/inline/CII34tF1iLzVmukc6B5ELcUC-qGR0wmxhbxd6wmpNGvrYk_PhpbgDsEQRokr_WM0x17ILfP3Oy1IBgVw4bV-XIQEhBkcUm1d497nqk-Pss5SM3T2BPZ5wdLAZn82SiubvjKa5KkaedGeEcXEXffEDsc2/file# [following]
--2023-11-24 18:19:42--  https://ucef4844c05faf416a67581341fc.dl.dropboxusercontent.com/cd/0/inline/CII34tF1iLzVmukc6B5ELcUC-qGR0wmxhbxd6wmpNGvrYk_Phpb

In [3]:
with open('/content/socialmedia_relevant_cols.csv', encoding="utf8", errors='ignore') as f:
  text = f.read()

In [4]:
file = open('social_media.csv','w')
file.write(text)
file.close

<function TextIOWrapper.close()>

In [5]:
import pandas as pd
df1 = pd.read_csv('/content/social_media.csv')

In [6]:
pd.set_option('display.max_colwidth', -1)

<ipython-input-6-0891b765a168>:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)


In [7]:
df1.head(10)

text  \
0  Just happened a terrible car crash                                                                                                      
1  Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all                                                                   
2  Heard about #earthquake is different cities, stay safe everyone.                                                                        
3  there is a forest fire at spot pond, geese are fleeing across the street, I cannot save them all                                        
4  Forest fire near La Ronge Sask. Canada                                                                                                  
5  All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected   
6  13,000 people receive #wildfires evacuation orders in California                                                                        
7  Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school                                                 
8  #RockyFire Update => California Hwy. 20 closed in both directions due to Lake County fire - #CAfire #wildfires                          
9  Apocalypse lighting. #Spokane #wildfires                                                                                                

  choose_one  class_label  
0  Relevant   1            
1  Relevant   1            
2  Relevant   1            
3  Relevant   1            
4  Relevant   1            
5  Relevant   1            
6  Relevant   1            
7  Relevant   1            
8  Relevant   1            
9  Relevant   1

In [8]:
print(df1.choose_one.unique())
print(df1.class_label.unique())

['Relevant' 'Not Relevant' "Can't Decide"]
[1 0 2]


In [9]:
df1.groupby(['choose_one','class_label']).count()

text
choose_one   class_label      
Can't Decide 2            16  
Not Relevant 0            6187
Relevant     1            4673

In [10]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopword=stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [11]:
df1['text']=df1['text'].str.lower()


In [12]:
import re
df1['text']=df1['text'].apply(lambda x:re.sub(r'(http)+\S*','',x))
df1['text']=df1['text'].apply(lambda x:re.sub(r'[^a-z\s]','',x))
li=list()
for i in df1['text'][:]:
 words=i.split()
 t=[word for word in words if word not in stopword and len(word)>2
]
 li.append(' '.join(t))

In [13]:
df1['clean']=li
df1.head()

text  \
0  just happened a terrible car crash                                                               
1  our deeds are the reason of this earthquake may allah forgive us all                             
2  heard about earthquake is different cities stay safe everyone                                    
3  there is a forest fire at spot pond geese are fleeing across the street i cannot save them all   
4  forest fire near la ronge sask canada                                                            

  choose_one  class_label  \
0  Relevant   1             
1  Relevant   1             
2  Relevant   1             
3  Relevant   1             
4  Relevant   1             

                                                           clean  
0  happened terrible car crash                                    
1  deeds reason earthquake may allah forgive                      
2  heard earthquake different cities stay safe everyone           
3  forest fire spot pond geese fleeing across street cannot save  
4  forest fire near ronge sask canada

In [14]:
from nltk.tokenize import RegexpTokenizer
regex = RegexpTokenizer(r'\w+')
df1['tokens'] = df1.clean.apply(lambda x : regex.tokenize(x))

In [15]:
df1.head()

text  \
0  just happened a terrible car crash                                                               
1  our deeds are the reason of this earthquake may allah forgive us all                             
2  heard about earthquake is different cities stay safe everyone                                    
3  there is a forest fire at spot pond geese are fleeing across the street i cannot save them all   
4  forest fire near la ronge sask canada                                                            

  choose_one  class_label  \
0  Relevant   1             
1  Relevant   1             
2  Relevant   1             
3  Relevant   1             
4  Relevant   1             

                                                           clean  \
0  happened terrible car crash                                     
1  deeds reason earthquake may allah forgive                       
2  heard earthquake different cities stay safe everyone            
3  forest fire spot pond geese fleeing across street cannot save   
4  forest fire near ronge sask canada                              

                                                                     tokens  
0  [happened, terrible, car, crash]                                          
1  [deeds, reason, earthquake, may, allah, forgive]                          
2  [heard, earthquake, different, cities, stay, safe, everyone]              
3  [forest, fire, spot, pond, geese, fleeing, across, street, cannot, save]  
4  [forest, fire, near, ronge, sask, canada]

In [16]:
from sklearn.model_selection import train_test_split
df1.drop('choose_one',axis=1,inplace=True)
X = df1.drop('class_label',axis=1)
y = df1["class_label"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)
print("Shape of Training set",X_train.shape)
print("Shape of Testing set",X_test.shape)

Shape of Training set (8700, 3)
Shape of Testing set (2176, 3)


In [17]:
complete=' '.join(X_train['clean'])
vocab=set(complete.split())
len(vocab)

17967

In [18]:
from collections import Counter
count_vocab = Counter(complete.split())
count_vocab.most_common(20)

[('like', 379),
 ('amp', 325),
 ('fire', 286),
 ('get', 274),
 ('via', 265),
 ('new', 254),
 ('news', 239),
 ('one', 231),
 ('people', 215),
 ('dont', 208),
 ('video', 185),
 ('emergency', 184),
 ('disaster', 173),
 ('would', 168),
 ('police', 164),
 ('time', 145),
 ('still', 142),
 ('suicide', 140),
 ('body', 139),
 ('storm', 136)]

In [19]:
from gensim.models import Word2Vec

model_vec_train = Word2Vec(
    sentences=X_train['tokens'],
    vector_size=200,
    window=5,
    min_count=5,
    workers=-1,
    sg=1
)

In [20]:
model_vec_train.wv.get_vector('like').shape

(200,)

In [21]:
X_train.head()

text  \
63    soooo pumped for ablaze  southridgelife                                                                                            
1460  good diss bad beat and flow mark my words meek mill is body bagging him once he responds patient patient meek is a battle rapper   
6095  im melting a bar of chocolate under my laptop at least this fucking hellfire is good for something                                 
7610  pandemoniumiso psp                                                                                                                 
221   usama bin ladins family dead in airplane crash naturally no accident                                                               

                                                                                                      clean  \
63    soooo pumped ablaze southridgelife                                                                      
1460  good diss bad beat flow mark words meek mill body bagging responds patient patient meek battle rapper   
6095  melting bar chocolate laptop least fucking hellfire good something                                      
7610  pandemoniumiso psp                                                                                      
221   usama bin ladins family dead airplane crash naturally accident                                          

                                                                                                                       tokens  
63    [soooo, pumped, ablaze, southridgelife]                                                                                  
1460  [good, diss, bad, beat, flow, mark, words, meek, mill, body, bagging, responds, patient, patient, meek, battle, rapper]  
6095  [melting, bar, chocolate, laptop, least, fucking, hellfire, good, something]                                             
7610  [pandemoniumiso, psp]                                                                                                    
221   [usama, bin, ladins, family, dead, airplane, crash, naturally, accident]

In [51]:
import numpy as np

def get_embeddings(data, model=model_vec_train):
    if isinstance(data, str):  # If it's a string (single sentence), tokenize it
        tokens = data.split()  # Modify this tokenization as per your need
    elif isinstance(data, list):  # If it's a list of tokens
        tokens = data
    else:
        raise ValueError("Unsupported data format")

    vectors = [model.wv[word] if word in model.wv else np.zeros(200) for word in tokens]
    valid_vectors = [vec for vec in vectors if vec.any()]

    if valid_vectors:
        return np.mean(valid_vectors, axis=0)
    else:
        return np.zeros(200)


In [52]:
def generate_embeddings(data, model=model_vec_train):
    embeddings = data.apply(lambda x: get_embeddings(x, model))
    return embeddings


In [24]:
X_train.head()

text  \
63    soooo pumped for ablaze  southridgelife                                                                                            
1460  good diss bad beat and flow mark my words meek mill is body bagging him once he responds patient patient meek is a battle rapper   
6095  im melting a bar of chocolate under my laptop at least this fucking hellfire is good for something                                 
7610  pandemoniumiso psp                                                                                                                 
221   usama bin ladins family dead in airplane crash naturally no accident                                                               

                                                                                                      clean  \
63    soooo pumped ablaze southridgelife                                                                      
1460  good diss bad beat flow mark words meek mill body bagging responds patient patient meek battle rapper   
6095  melting bar chocolate laptop least fucking hellfire good something                                      
7610  pandemoniumiso psp                                                                                      
221   usama bin ladins family dead airplane crash naturally accident                                          

                                                                                                                       tokens  
63    [soooo, pumped, ablaze, southridgelife]                                                                                  
1460  [good, diss, bad, beat, flow, mark, words, meek, mill, body, bagging, responds, patient, patient, meek, battle, rapper]  
6095  [melting, bar, chocolate, laptop, least, fucking, hellfire, good, something]                                             
7610  [pandemoniumiso, psp]                                                                                                    
221   [usama, bin, ladins, family, dead, airplane, crash, naturally, accident]

In [53]:
embeddings_train=generate_embeddings(X_train['tokens'])
embeddings_test=generate_embeddings(X_test['tokens'])

In [54]:
embeddings_test.sample

<bound method NDFrame.sample of 410      [0.0012603023, -0.0005857042, -0.002509457, -0.00044046482, -0.001156842, -0.0011515161, 0.0022444539, -0.0010102848, -0.0018341035, 0.0005718213, -3.0469102e-05, 0.0016707355, 0.0018159079, 0.00043755546, -0.0006354116, -0.0011072549, -3.4381264e-05, 0.0002666764, -0.0018130128, -0.001383051, 0.002490031, 0.0005250656, -0.0024227924, -0.0020224361, 0.00039707794, -0.0017489413, 0.0007145512, 0.0011538351, 0.001966338, 0.0002295109, 0.002468469, 0.0010256429, 0.002067713, -0.0016960036, 0.00024299226, 0.0016602004, -0.0001908232, -0.00035268813, 0.0004492613, 0.00019859483, 0.00049250264, -0.0031463213, 0.0006590708, 0.0017551143, -0.0013104273, 0.0002776423, -0.0003433589, 0.0013034133, 9.719888e-06, 0.0002608294, -0.0013352272, 0.0012415111, 0.00020250879, -0.0023443336, -0.00028479862, -0.0007576138, -0.000111184454, 0.0019583907, 0.0021189644, -0.00057011406, 0.0012214103, 0.00062408764, 0.0023029111, -0.0014465476, -0.0012145026, -0.0021447

In [27]:
d = {}
for i in range(200):
    l = []
    for j in range(8700):
        try:
            l.append(embeddings_train.values[j][i])
        except IndexError:
            l.append(0)
    d[i] = l

train = pd.DataFrame(d)


In [28]:
dic = {}
for i in range(200):
    l = []
    for j in range(2176):
        try:
            l.append(embeddings_test.values[j][i])
        except IndexError:
            l.append(0)
    dic[i] = l

test = pd.DataFrame(dic)


In [29]:
print(train.shape)
print(test.shape)


(8700, 200)
(2176, 200)


In [30]:
train.head

<bound method NDFrame.head of              0         1         2         3         4         5         6  \
0    -0.002584 -0.004744 -0.000696 -0.000022 -0.003367  0.000145 -0.004634   
1     0.001160  0.000495 -0.000798 -0.000511 -0.000427  0.001138  0.000437   
2    -0.001007  0.000428 -0.001266 -0.000862 -0.003310  0.000319 -0.001189   
3     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4     0.000265  0.000969  0.001577  0.000202  0.001255 -0.001538 -0.001708   
...        ...       ...       ...       ...       ...       ...       ...   
8695 -0.002698  0.000220 -0.001807  0.003359  0.001303  0.002556 -0.002887   
8696  0.000408 -0.000224  0.000379 -0.000058 -0.001003 -0.000452  0.000187   
8697  0.002480  0.002207 -0.001445  0.000040  0.001435  0.001414  0.001649   
8698 -0.000733  0.001153  0.000334  0.000657  0.001914 -0.000022 -0.001623   
8699  0.003511 -0.002641 -0.000904  0.002042  0.001719  0.001224  0.001073   

             7         8         

In [31]:
test.head

<bound method NDFrame.head of              0         1         2         3         4         5         6  \
0     0.001260 -0.000586 -0.002509 -0.000440 -0.001157 -0.001152  0.002244   
1    -0.001555  0.002932 -0.002327 -0.001439  0.001184  0.002100 -0.001955   
2    -0.000555  0.000691 -0.000251  0.001655  0.000069  0.000130 -0.000071   
3     0.000760  0.000615  0.000258  0.000531  0.000302  0.001553 -0.000917   
4    -0.001517 -0.000733  0.000528  0.001762  0.001399  0.001594 -0.000704   
...        ...       ...       ...       ...       ...       ...       ...   
2171  0.000140 -0.000553 -0.000501 -0.001482 -0.000343  0.001835 -0.002574   
2172 -0.000358  0.001236  0.001271 -0.000039 -0.000515  0.001433  0.001041   
2173  0.001284 -0.000081 -0.001423  0.001064 -0.000870 -0.000454 -0.000044   
2174 -0.004446  0.003287  0.003483 -0.004516 -0.001265 -0.004040  0.001524   
2175 -0.001687  0.001894 -0.000399  0.000890 -0.000330  0.000231 -0.001575   

             7             8     

In [32]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
models=[]
models.append(('lr',LogisticRegression()))
models.append(('decision tree',DecisionTreeClassifier()))
models.append(('svm',SVC(gamma='auto')))
models.append(('knn',KNeighborsClassifier()))
models.append(('gaussian naive bayes',GaussianNB()))
models.append(('Random Forest',RandomForestClassifier()))
for name,model in models:
    kfold=KFold(n_splits=10)
    cross_val_sc=cross_val_score(model,train,y_train,scoring='accuracy',cv=kfold)
    print('{} : acc: {}(standard deviation: {})'.format(name,cross_val_sc.mean(),cross_val_sc.std()))

lr : acc: 0.5648275862068965(standard deviation: 0.018109924037913682)
decision tree : acc: 0.6180459770114942(standard deviation: 0.011989888724630134)
svm : acc: 0.5648275862068965(standard deviation: 0.018109924037913682)
knn : acc: 0.7008045977011494(standard deviation: 0.018101532465678825)
gaussian naive bayes : acc: 0.55(standard deviation: 0.015276982047282183)
Random Forest : acc: 0.7166666666666668(standard deviation: 0.01368974685590383)


In [33]:
from sklearn.ensemble import RandomForestClassifier
final_model= RandomForestClassifier()
final_model.fit(train,y_train)
final_model.score(train,y_train)

0.9780459770114942

In [34]:
y_pred = final_model.predict(test)

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1158  115    0]
 [ 507  392    0]
 [   4    0    0]]
0.7123161764705882


In [ ]:
y_pred=final_model.predict(prep)

In [37]:
import re
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords

stopwords = set(stopwords.words('english'))

def preprocess_input(text):
    text = text.lower()

    text = re.sub(r'(http)+\S*','', text)
    text = re.sub(r'[^a-z\s]','', text)
    tokenizer = RegexpTokenizer(r'\w+')
    tokens = tokenizer.tokenize(text)
    filtered_tokens = [token for token in tokens if token not in stopwords and len(token) > 2]

    return filtered_tokens


In [77]:
input_text = "Fuck the police"
prep = preprocess_input(input_text)

In [79]:
prep

['fuck', 'police']

In [78]:
def generate_embeddings1(data, model=model_vec_train):
    embeddings = [get_embeddings(tokens, model) for tokens in data]
    return embeddings

In [80]:
embeddings = generate_embeddings1(prep)

In [69]:
embeddings

[array([-4.8464658e-03, -3.4918778e-03,  4.2093880e-03,  2.9772026e-03,
         4.9922792e-03,  4.8598289e-04,  9.6260069e-04,  9.4922126e-04,
        -4.4821631e-03,  1.9201827e-03, -3.2440126e-03,  4.0840749e-03,
        -4.7665061e-03, -3.9608623e-03,  3.2383280e-03, -1.9689447e-03,
         4.9988711e-03, -4.4224598e-03, -4.5925201e-04, -4.4533145e-03,
         1.0090339e-03, -1.3721919e-03,  3.9751120e-03,  3.0523897e-03,
         1.2933927e-03,  3.1334227e-03, -4.3419246e-03,  2.0170212e-06,
         2.3426169e-03,  2.1081953e-03, -2.0618970e-03, -3.9802007e-03,
         2.9901010e-03,  4.5416080e-03, -2.8375841e-03, -1.3716834e-03,
        -3.0620676e-03,  1.2079257e-03,  4.0106857e-03,  1.8950987e-03,
         2.4729830e-03,  4.7318675e-03,  1.5361458e-03,  8.8900386e-04,
         3.4891807e-03, -2.8308553e-03,  2.6865643e-03,  3.9569158e-03,
         9.4067218e-04,  1.6615808e-03, -2.1883678e-03,  8.2953571e-04,
        -2.3018115e-03, -1.1202133e-03,  1.4828146e-03, -1.72712

In [70]:
pred=final_model.predict(embeddings)

In [71]:
pred

array([0, 0, 1])

In [ ]:
predtest=final_model.predict(test)

In [ ]:
predtest

In [81]:
import numpy as np

predicted_probabilities = final_model.predict_proba(embeddings)

predicted_classes = np.argmax(predicted_probabilities, axis=1)

class_labels = {
    0: 'Not relevant',
    1: 'Relevant',
    2: "Can't decide"
}

predicted_labels = [class_labels[i] for i in predicted_classes]

print(predicted_labels)


['Not relevant', 'Relevant']
